// <auto-generated />
namespace DesignPatterns.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class Cascade_New : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cascade_New));
        
        string IMigrationMetadata.Id
        {
            get { return "201912091933279_Cascade_New"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
